### ISSUE TITLE
Error in Audio Producer causing audio component to crash

### ISSUE THREAD

**Issue by g3ar-v** [g3ar-v/vasco#16]
00:12:01.423 | ERROR    | 11873 | core.client.voice.listener:run:94 | Exception in AudioProducer
Traceback (most recent call last):
  File "/Users/g3ar/Projects/__core__/core/client/voice/listener.py", line 69, in run
    audio = self.recognizer.listen(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/g3ar/Projects/__core__/core/client/voice/mic.py", line 748, in listen
    if ww_data.found:
       ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'found'
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/opt/miniconda3/envs/core/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Users/g3ar/Projects/__core__/core/client/voice/listener.py", line 69, in run
    audio = self.recognizer.listen(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/g3ar/Projects/__core__/core/client/voice/mic.py", line 748, in listen
    if ww_data.found:
       ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'found'

**Comment by g3ar-v** [comment]
this happens when you trigger another wakeword after previously calling one

**Comment by g3ar-v** [comment]
fixed in this commit [f1719b1](https://github.com/g3ar-v/__core__/commit/f1719b1d6a0c82511a5d52de1013615471e22eb9)
