### ISSUE TITLE
config: configuration can't be changed at runtime

### ISSUE THREAD

**Issue by g3ar-v** [g3ar-v/vasco#19]
2023-10-18 14:13:55.986 | ERROR    | 32500 | core.configuration.config:load_local:103 | Error loading configuration '/Users/g3ar/.config/core/core.conf'
2023-10-18 14:13:55.987 | ERROR    | 32500 | core.configuration.config:load_local:104 | AttributeError("'NoneType' object has no attribute 'level'")
2023-10-18 14:13:55.988 | ERROR    | 32500 | concurrent.futures | exception calling callback for <Future at 0x2a9a2b410 state=finished raised AttributeError>
Traceback (most recent call last):
  File "/opt/miniconda3/envs/core/lib/python3.11/concurrent/futures/_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "/Users/g3ar/.local/lib/python3.11/site-packages/pyee/_executor.py", line 56, in _callback
    self.emit('error', exc)
  File "/Users/g3ar/.local/lib/python3.11/site-packages/pyee/_base.py", line 116, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/Users/g3ar/.local/lib/python3.11/site-packages/pyee/_base.py", line 86, in _emit_handle_potential_error
    raise error
  File "/opt/miniconda3/envs/core/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/g3ar/Projects/__core__/core/configuration/config.py", line 281, in updated
    Configuration.load_config_stack(cache=True)
  File "/Users/g3ar/Projects/__core__/core/configuration/config.py", line 232, in load_config_stack
    configs.append(LocalConf(SYSTEM_CONFIG))
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/g3ar/Projects/__core__/core/configuration/config.py", line 87, in __init__
    self.load_local(path)
  File "/Users/g3ar/Projects/__core__/core/configuration/config.py", line 107, in load_local
    LOG.debug("Configuration '{}' not defined, skipping".format(path))
  File "/Users/g3ar/Projects/__core__/core/util/log.py", line 25, in method
    cls._log(fn, *args, **kwargs)
  File "/Users/g3ar/Projects/__core__/core/util/log.py", line 117, in _log
    func(cls.create_logger(name), *args, **kwargs)
  File "/opt/miniconda3/envs/core/lib/python3.11/logging/__init__.py", line 1477, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/opt/miniconda3/envs/core/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/opt/miniconda3/envs/core/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/opt/miniconda3/envs/core/lib/python3.11/logging/__init__.py", line 1705, in callHandlers
    if record.levelno >= hdlr.level:
                         ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'level'

**Comment by g3ar-v** [comment]
fixed in https://github.com/g3ar-v/__core__/commit/0c303c2e615b026d079d1fb852f3e8836dc911fd
